# version: 2.1
# jobs:
#   test_node_6:
#      - image: circleci/node:6
#      steps:
#       - checkout
#       - run:
#           name: install
#           command: npm install
#       - run:
#           name: lint
#           command: npm run lint
#       - run:
#           name: test
#           command: npm test
#       - run:
#           name: coverage
#           command: npm run coverage
#       - run:
#           name: release
#           command: npm run semantic-release || true
#   build:
#     docker:
#       - image: "circleci/node:latest"
#     steps:
#       - checkout
#       - run:
#           name: install
#           command: npm install
#       - run:
#           name: lint
#           command: npm run lint
#       - run:
#           name: test
#           command: npm test
#       - run:
#           name: coverage
#           command: npm run coverage
#       - run:
#           name: release
#           command: npm run semantic-release || true


version: 2
jobs:
  test_node_8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm test
      - run:
          name: coverage
          command: npm run coverage
      # - run:
      #     name: release
      #     command: npm run semantic-release || true
  test_node_10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm test
      - run:
          name: coverage
          command: npm run coverage
      # - run:
      #     name: release
      #     command: npm run semantic-release || true

  release:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npx semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test_node_8
      - test_node_10
      - release:
          requires:
            - test_node_8
            - test_node_10
